---
- name: Setup Apache web server with custom index page
  hosts: all
  become: true

  tasks:
    - name: Install Apache
      ansible.builtin.package:
        name: apache2
        state: present
        update_cache: yes

    - name: Deploy custom index.html
      ansible.builtin.copy:
        dest: /var/www/html/index.html
        content:
          <html>
            <head></head>
            <body>
              <h1>Hi! My name is Ife, Hello from Ansible</h1>
            </body>
          </html>
        owner: root
        group: root
        mode: '0644'

    - name: Set timezone to Africa/Lagos
      ansible.builtin.timezone:
        name: Africa/Lagos

    - name: Ensure Apache service is started and enabled on boot
      ansible.builtin.systemd:
        name: apache2
        state: started
        enabled: yes

    - name: Install UFW firewall
      ansible.builtin.apt:
        name: ufw
        state: present
        update_cache: yes

    - name: Open HTTP port 80 in UFW firewall
      ansible.builtin.ufw:
        rule: allow
        port: '80'
        proto: tcp

    - name: Enable UFW firewall
      ansible.builtin.ufw:
        state: enabled